
/*
 * This file was generated by the SOM Compiler.
 * FileName: d:\work\c\wpsac\wpsac3\wpsac.h.
 * Generated using:
 *     SOM Precompiler somipc: 2.29.1.7
 *     SOM Emitter emith: 2.42
 */

/*
 * 
 * 
 *    Module Name: WPSac
 * 
 *    OS/2 Workplace Shell Access Controll
 * 
 */


#ifndef SOM_WPSac_h
#define SOM_WPSac_h


#include <som.h>

/*
 * -- This emitter treats Method Tokens as Thunks by default.
 * -- Use the sc modifier "nothunks" to change this default
 */
#undef somresolve_
#define somresolve_(obj,mToken) ((somMethodProc*)((void)obj, mToken))

/*
 * Define the class name as an object type
 */
#ifndef WPSac
#define WPSac SOMObject
#endif
#include <wpobject.h>

/*
 * Start of user-defined types:
 */
#ifndef SOMClass
    #define SOMClass SOMObject
#endif /* SOMClass */
#ifndef WPFolder
    #define WPFolder SOMObject
#endif /* WPFolder */
#ifndef M_WPObject
    #define M_WPObject SOMObject
#endif /* M_WPObject */
#ifndef WPObject
    #define WPObject SOMObject
#endif /* WPObject */
#ifndef M_WPSac
    #define M_WPSac SOMObject
#endif /* M_WPSac */

/*
 * End of user-defined types.
 */

/*
 * Passthru lines: File: "C.h", "after"
 */



#define WPSac_MajorVersion 1
#define WPSac_MinorVersion 1

/*
 * External name shortening if required
 */
#ifdef SOM_USE_SHORT_EXTERNAL_NAMES
#define WPSacNewClass wpSacc
#pragma linkage(wpSacc, system)
#define WPSacClassData wpSacd
#define WPSacCClassData wpSacx
#endif /* SOM_USE_SHORT_EXTERNAL_NAMES */

/*
 * Include the meta class file
 */
#include <wpsac.h>
/*--------------Migration------------*/
#define WPSac_classObj WPSacClassData.classObject
#define _WPSac WPSac_classObj

/*
 * Declare the class creation procedure
 */
SOMEXTERN SOMClass * SOMLINK WPSacNewClass(integer4 somtmajorVersion,
		integer4 somtminorVersion);
#pragma linkage(WPSacNewClass, system)

/*
 * Declare the class data structure
 */
SOMEXTERN struct WPSacClassDataStructure {
	SOMClass *classObject;
	somMToken AccessControl;
	somMToken NewStyle;
} SOMDLINK WPSacClassData;

/*
 * Declare the C specific class data structure
 */
SOMEXTERN struct WPSacCClassDataStructure {
	somMethodTabs parentMtab;
	somDToken instanceDataToken;
} SOMDLINK WPSacCClassData;

/*
 * New and Renew macros for WPSac
 */
#define WPSacNew() \
   (_somNew(_WPSac ? _WPSac : WPSacNewClass(WPSac_MajorVersion, WPSac_MinorVersion)))
#define WPSacRenew(buf) \
   (_somRenew(_WPSac ? _WPSac : WPSacNewClass(WPSac_MajorVersion, WPSac_MinorVersion), buf))

/*
 * Override method: wpFilterPopupMenu
 */
#define WPSac_wpFilterPopupMenu(somSelf,ulFlags,hwndCnr,fMultiSelect) \
	WPObject_wpFilterPopupMenu(somSelf,ulFlags,hwndCnr,fMultiSelect)

/*
 * Override method: wpInitData
 */
#define WPSac_wpInitData(somSelf) \
	WPObject_wpInitData(somSelf)

/*
 * Override method: wpMenuItemSelected
 */
#define WPSac_wpMenuItemSelected(somSelf,hwndFrame,ulMenuId) \
	WPObject_wpMenuItemSelected(somSelf,hwndFrame,ulMenuId)

/*
 * Override method: wpModifyPopupMenu
 */
#define WPSac_wpModifyPopupMenu(somSelf,hwndMenu,hwndCnr,iPosition) \
	WPObject_wpModifyPopupMenu(somSelf,hwndMenu,hwndCnr,iPosition)

/*
 * Override method: wpQueryDefaultView
 */
#define WPSac_wpQueryDefaultView(somSelf) \
	WPObject_wpQueryDefaultView(somSelf)

/*
 * Override method: wpRestoreState
 */
#define WPSac_wpRestoreState(somSelf,ulReserved) \
	WPObject_wpRestoreState(somSelf,ulReserved)

/*
 * Override method: wpSaveState
 */
#define WPSac_wpSaveState(somSelf) \
	WPObject_wpSaveState(somSelf)

/*
 * Override method: wpOpen
 */
#define WPSac_wpOpen(somSelf,hwndCnr,ulView,param) \
	WPObject_wpOpen(somSelf,hwndCnr,ulView,param)

/*
 * New Method: AccessControl
 */
typedef void   SOMLINK somTP_WPSac_AccessControl(WPSac *somSelf);
#pragma linkage(somTP_WPSac_AccessControl, system)
typedef somTP_WPSac_AccessControl *somTD_WPSac_AccessControl;
#define somMD_WPSac_AccessControl "::WPSac::AccessControl"
#define WPSac_AccessControl(somSelf) \
    (SOM_Resolve(somSelf, WPSac, AccessControl) \
	(somSelf))
#ifndef SOMGD_AccessControl
    #if (defined(_AccessControl) || defined(__AccessControl))
        #undef _AccessControl
        #undef __AccessControl
        #define SOMGD_AccessControl 1
    #else
        #define _AccessControl WPSac_AccessControl
    #endif /* _AccessControl */
#endif /* SOMGD_AccessControl */

/*
 * New Method: NewStyle
 */
typedef void   SOMLINK somTP_WPSac_NewStyle(WPSac *somSelf,
		ULONG ulAND_STYLE,
		ULONG ulOR_STYLE);
#pragma linkage(somTP_WPSac_NewStyle, system)
typedef somTP_WPSac_NewStyle *somTD_WPSac_NewStyle;
#define somMD_WPSac_NewStyle "::WPSac::NewStyle"
#define WPSac_NewStyle(somSelf,ulAND_STYLE,ulOR_STYLE) \
    (SOM_Resolve(somSelf, WPSac, NewStyle) \
	(somSelf,ulAND_STYLE,ulOR_STYLE))
#ifndef SOMGD_NewStyle
    #if (defined(_NewStyle) || defined(__NewStyle))
        #undef _NewStyle
        #undef __NewStyle
        #define SOMGD_NewStyle 1
    #else
        #define _NewStyle WPSac_NewStyle
    #endif /* _NewStyle */
#endif /* SOMGD_NewStyle */
#ifndef SOM_DONT_USE_INHERITED_MACROS
#define WPSac_wpAddObjectGeneralPage WPObject_wpAddObjectGeneralPage
#define WPSac_wpAddObjectGeneralPage2 WPObject_wpAddObjectGeneralPage2
#define WPSac_wpAddObjectWindowPage WPObject_wpAddObjectWindowPage
#define WPSac_wpAddSettingsPages WPObject_wpAddSettingsPages
#define WPSac_wpAddToObjUseList WPObject_wpAddToObjUseList
#define WPSac_wpAllocMem WPObject_wpAllocMem
#define WPSac_wpAppendObject WPObject_wpAppendObject
#define WPSac_wpAssertObjectMutexSem WPObject_wpAssertObjectMutexSem
#define WPSac_wpClose WPObject_wpClose
#define WPSac_wpCnrInsertObject WPObject_wpCnrInsertObject
#define WPSac_wpCnrRemoveObject WPObject_wpCnrRemoveObject
#define WPSac_wpCnrSetEmphasis WPObject_wpCnrSetEmphasis
#define WPSac_wpConfirmDelete WPObject_wpConfirmDelete
#define WPSac_wpConfirmObjectTitle WPObject_wpConfirmObjectTitle
#define WPSac_wpCopiedFromTemplate WPObject_wpCopiedFromTemplate
#define WPSac_wpCopyObject WPObject_wpCopyObject
#define WPSac_wpCreateAnother WPObject_wpCreateAnother
#define WPSac_wpCreateFromTemplate WPObject_wpCreateFromTemplate
#define WPSac_wpCreateShadowObject WPObject_wpCreateShadowObject
#define WPSac_wpDelete WPObject_wpDelete
#define WPSac_wpDeleteFromObjUseList WPObject_wpDeleteFromObjUseList
#define WPSac_wpDisplayHelp WPObject_wpDisplayHelp
#define WPSac_wpDisplayMenu WPObject_wpDisplayMenu
#define WPSac_wpDoesObjectMatch WPObject_wpDoesObjectMatch
#define WPSac_wpDraggedOverObject WPObject_wpDraggedOverObject
#define WPSac_wpDragOver WPObject_wpDragOver
#define WPSac_wpDrop WPObject_wpDrop
#define WPSac_wpDroppedOnObject WPObject_wpDroppedOnObject
#define WPSac_wpEndConversation WPObject_wpEndConversation
#define WPSac_wpFindUseItem WPObject_wpFindUseItem
#define WPSac_wpFormatDragItem WPObject_wpFormatDragItem
#define WPSac_wpFree WPObject_wpFree
#define WPSac_wpFreeMem WPObject_wpFreeMem
#define WPSac_wpHide WPObject_wpHide
#define WPSac_wpInsertPopupMenuItems WPObject_wpInsertPopupMenuItems
#define WPSac_wpInsertSettingsPage WPObject_wpInsertSettingsPage
#define WPSac_wpMenuItemHelpSelected WPObject_wpMenuItemHelpSelected
#define WPSac_wpMoveObject WPObject_wpMoveObject
#define WPSac_wpPrintObject WPObject_wpPrintObject
#define WPSac_wpQueryConcurrentView WPObject_wpQueryConcurrentView
#define WPSac_wpQueryButtonAppearance WPObject_wpQueryButtonAppearance
#define WPSac_wpQueryConfirmations WPObject_wpQueryConfirmations
#define WPSac_wpQueryDefaultHelp WPObject_wpQueryDefaultHelp
#define WPSac_wpQueryDetailsData WPObject_wpQueryDetailsData
#define WPSac_wpQueryError WPObject_wpQueryError
#define WPSac_wpSetFolder WPObject_wpSetFolder
#define WPSac_wpQueryFolder WPObject_wpQueryFolder
#define WPSac_wpQueryIcon WPObject_wpQueryIcon
#define WPSac_wpQueryIconData WPObject_wpQueryIconData
#define WPSac_wpQueryMinWindow WPObject_wpQueryMinWindow
#define WPSac_wpQueryNameClashOptions WPObject_wpQueryNameClashOptions
#define WPSac_wpQueryStyle WPObject_wpQueryStyle
#define WPSac_wpSetTaskRec WPObject_wpSetTaskRec
#define WPSac_wpFindTaskRec WPObject_wpFindTaskRec
#define WPSac_wpQueryTitle WPObject_wpQueryTitle
#define WPSac_wpRegisterView WPObject_wpRegisterView
#define WPSac_wpReleaseObjectMutexSem WPObject_wpReleaseObjectMutexSem
#define WPSac_wpRender WPObject_wpRender
#define WPSac_wpRenderComplete WPObject_wpRenderComplete
#define WPSac_wpReplaceObject WPObject_wpReplaceObject
#define WPSac_wpRequestObjectMutexSem WPObject_wpRequestObjectMutexSem
#define WPSac_wpRestore WPObject_wpRestore
#define WPSac_wpRestoreData WPObject_wpRestoreData
#define WPSac_wpRestoreLong WPObject_wpRestoreLong
#define WPSac_wpRestoreString WPObject_wpRestoreString
#define WPSac_wpSaveData WPObject_wpSaveData
#define WPSac_wpSaveImmediate WPObject_wpSaveImmediate
#define WPSac_wpSaveDeferred WPObject_wpSaveDeferred
#define WPSac_wpSaveLong WPObject_wpSaveLong
#define WPSac_wpSaveString WPObject_wpSaveString
#define WPSac_wpScanSetupString WPObject_wpScanSetupString
#define WPSac_wpSetConcurrentView WPObject_wpSetConcurrentView
#define WPSac_wpSetButtonAppearance WPObject_wpSetButtonAppearance
#define WPSac_wpSetDefaultHelp WPObject_wpSetDefaultHelp
#define WPSac_wpSetDefaultView WPObject_wpSetDefaultView
#define WPSac_wpSetError WPObject_wpSetError
#define WPSac_wpSetIconHandle WPObject_wpSetIconHandle
#define WPSac_wpQueryScreenGroupID WPObject_wpQueryScreenGroupID
#define WPSac_wpSetupOnce WPObject_wpSetupOnce
#define WPSac_wpSetIcon WPObject_wpSetIcon
#define WPSac_wpSetIconData WPObject_wpSetIconData
#define WPSac_wpSetMinWindow WPObject_wpSetMinWindow
#define WPSac_wpSetStyle WPObject_wpSetStyle
#define WPSac_wpModifyStyle WPObject_wpModifyStyle
#define WPSac_wpSetTitle WPObject_wpSetTitle
#define WPSac_wpSetup WPObject_wpSetup
#define WPSac_wpSwitchTo WPObject_wpSwitchTo
#define WPSac_wpUnInitData WPObject_wpUnInitData
#define WPSac_wpViewObject WPObject_wpViewObject
#define WPSac_wpQueryTrueStyle WPObject_wpQueryTrueStyle
#define WPSac_wpQueryHandle WPObject_wpQueryHandle
#define WPSac_wpUnlockObject WPObject_wpUnlockObject
#define WPSac_wpObjectReady WPObject_wpObjectReady
#define WPSac_wpIsObjectInitialized WPObject_wpIsObjectInitialized
#define WPSac_wpCreateShadowObjectExt WPObject_wpCreateShadowObjectExt
#define WPSac_wpCnrDeleteUseItem WPObject_wpCnrDeleteUseItem
#define WPSac_wpIsDeleteable WPObject_wpIsDeleteable
#define WPSac_wpQueryCoreRecord WPObject_wpQueryCoreRecord
#define WPSac_wpSetObjectID WPObject_wpSetObjectID
#define WPSac_wpQueryObjectID WPObject_wpQueryObjectID
#define WPSac_wpSetDefaultIconPos WPObject_wpSetDefaultIconPos
#define WPSac_wpQueryDefaultIconPos WPObject_wpQueryDefaultIconPos
#define WPSac_wpCnrRefreshDetails WPObject_wpCnrRefreshDetails
#define WPSac_wpFindViewItem WPObject_wpFindViewItem
#define WPSac_wpLockObject WPObject_wpLockObject
#define WPSac_wpIsLocked WPObject_wpIsLocked
#define WPSac_wpQueryContainerFlagPtr WPObject_wpQueryContainerFlagPtr
#define WPSac_wpWaitForClose WPObject_wpWaitForClose
#define WPSac_somDefaultInit SOMObject_somDefaultInit
#define WPSac_somDestruct SOMObject_somDestruct
#define WPSac_somDefaultCopyInit SOMObject_somDefaultCopyInit
#define WPSac_somDefaultAssign SOMObject_somDefaultAssign
#define WPSac_somDefaultConstCopyInit SOMObject_somDefaultConstCopyInit
#define WPSac_somDefaultVCopyInit SOMObject_somDefaultVCopyInit
#define WPSac_somDefaultConstVCopyInit SOMObject_somDefaultConstVCopyInit
#define WPSac_somDefaultConstAssign SOMObject_somDefaultConstAssign
#define WPSac_somDefaultVAssign SOMObject_somDefaultVAssign
#define WPSac_somDefaultConstVAssign SOMObject_somDefaultConstVAssign
#define WPSac_somInit SOMObject_somInit
#define WPSac_somFree SOMObject_somFree
#define WPSac_somUninit SOMObject_somUninit
#define WPSac_somGetClass SOMObject_somGetClass
#define WPSac_somGetClassName SOMObject_somGetClassName
#define WPSac_somGetSize SOMObject_somGetSize
#define WPSac_somIsA SOMObject_somIsA
#define WPSac_somIsInstanceOf SOMObject_somIsInstanceOf
#define WPSac_somRespondsTo SOMObject_somRespondsTo
#define WPSac_somDispatch SOMObject_somDispatch
#define WPSac_somClassDispatch SOMObject_somClassDispatch
#define WPSac_somCastObj SOMObject_somCastObj
#define WPSac_somResetObj SOMObject_somResetObj
#define WPSac_somDispatchV SOMObject_somDispatchV
#define WPSac_somDispatchL SOMObject_somDispatchL
#define WPSac_somDispatchA SOMObject_somDispatchA
#define WPSac_somDispatchD SOMObject_somDispatchD
#define WPSac_somPrintSelf SOMObject_somPrintSelf
#define WPSac_somDumpSelf SOMObject_somDumpSelf
#define WPSac_somDumpSelfInt SOMObject_somDumpSelfInt
#endif /* SOM_DONT_USE_INHERITED_MACROS */

#endif       /* SOM_WPSac_h */

#ifndef SOM_M_WPSac_h
#define SOM_M_WPSac_h


#include <som.h>

/*
 * -- This emitter treats Method Tokens as Thunks by default.
 * -- Use the sc modifier "nothunks" to change this default
 */
#undef somresolve_
#define somresolve_(obj,mToken) ((somMethodProc*)((void)obj, mToken))

/*
 * Define the class name as an object type
 */
#ifndef M_WPSac
#define M_WPSac SOMObject
#endif
#include <wpobject.h>

/*
 * Start of user-defined types:
 */

/*
 * End of user-defined types.
 */

#define M_WPSac_MajorVersion 1
#define M_WPSac_MinorVersion 1

/*
 * External name shortening if required
 */
#ifdef SOM_USE_SHORT_EXTERNAL_NAMES
#define M_WPSacNewClass c
#pragma linkage(c, system)
#define M_WPSacClassData d
#define M_WPSacCClassData x
#endif /* SOM_USE_SHORT_EXTERNAL_NAMES */
/*--------------Migration------------*/
#define M_WPSac_classObj M_WPSacClassData.classObject
#define _M_WPSac M_WPSac_classObj

/*
 * Declare the class creation procedure
 */
SOMEXTERN SOMClass * SOMLINK M_WPSacNewClass(integer4 somtmajorVersion,
		integer4 somtminorVersion);
#pragma linkage(M_WPSacNewClass, system)

/*
 * Declare the class data structure
 */
SOMEXTERN struct M_WPSacClassDataStructure {
	SOMClass *classObject;
} SOMDLINK M_WPSacClassData;

/*
 * Declare the C specific class data structure
 */
SOMEXTERN struct M_WPSacCClassDataStructure {
	somMethodTabs parentMtab;
	somDToken instanceDataToken;
} SOMDLINK M_WPSacCClassData;

/*
 * New and Renew macros for M_WPSac
 */
#define M_WPSacNew() \
   (_somNew(_M_WPSac ? _M_WPSac : M_WPSacNewClass(M_WPSac_MajorVersion, M_WPSac_MinorVersion)))
#define M_WPSacRenew(buf) \
   (_somRenew(_M_WPSac ? _M_WPSac : M_WPSacNewClass(M_WPSac_MajorVersion, M_WPSac_MinorVersion), buf))

/*
 * Override method: wpclsInitData
 */
#define M_WPSac_wpclsInitData(somSelf) \
	M_WPObject_wpclsInitData(somSelf)
#ifndef SOM_DONT_USE_INHERITED_MACROS
#define M_WPSac_wpclsCreateDefaultTemplates M_WPObject_wpclsCreateDefaultTemplates
#define M_WPSac_wpclsMakeAwake M_WPObject_wpclsMakeAwake
#define M_WPSac_wpclsNew M_WPObject_wpclsNew
#define M_WPSac_wpclsQueryDefaultHelp M_WPObject_wpclsQueryDefaultHelp
#define M_WPSac_wpclsQueryDefaultView M_WPObject_wpclsQueryDefaultView
#define M_WPSac_wpclsQueryDetails M_WPObject_wpclsQueryDetails
#define M_WPSac_wpclsQueryDetailsInfo M_WPObject_wpclsQueryDetailsInfo
#define M_WPSac_wpclsQueryExtendedCriteria M_WPObject_wpclsQueryExtendedCriteria
#define M_WPSac_wpclsQueryFolder M_WPObject_wpclsQueryFolder
#define M_WPSac_wpclsQueryIcon M_WPObject_wpclsQueryIcon
#define M_WPSac_wpclsQuerySearchInfo M_WPObject_wpclsQuerySearchInfo
#define M_WPSac_wpclsQueryStyle M_WPObject_wpclsQueryStyle
#define M_WPSac_wpclsQueryTitle M_WPObject_wpclsQueryTitle
#define M_WPSac_wpclsUnInitData M_WPObject_wpclsUnInitData
#define M_WPSac_wpclsFindObjectFirst M_WPObject_wpclsFindObjectFirst
#define M_WPSac_wpclsFindObjectNext M_WPObject_wpclsFindObjectNext
#define M_WPSac_wpclsFindObjectEnd M_WPObject_wpclsFindObjectEnd
#define M_WPSac_wpclsSetError M_WPObject_wpclsSetError
#define M_WPSac_wpclsQueryError M_WPObject_wpclsQueryError
#define M_WPSac_wpclsQuerySettingsPageSize M_WPObject_wpclsQuerySettingsPageSize
#define M_WPSac_wpclsQueryIconData M_WPObject_wpclsQueryIconData
#define M_WPSac_wpclsQueryObject M_WPObject_wpclsQueryObject
#define M_WPSac_wpclsQueryButtonAppearance M_WPObject_wpclsQueryButtonAppearance
#define M_WPSac_wpclsDecUsage M_WPObject_wpclsDecUsage
#define M_WPSac_wpclsIncUsage M_WPObject_wpclsIncUsage
#define M_WPSac_wpclsInsertMultipleObjects M_WPObject_wpclsInsertMultipleObjects
#define M_WPSac_wpclsFindOneObject M_WPObject_wpclsFindOneObject
#define M_WPSac_wpclsSetSettingsPageSize M_WPObject_wpclsSetSettingsPageSize
#define M_WPSac_wpclsSetIconData M_WPObject_wpclsSetIconData
#define M_WPSac_wpclsSetIcon M_WPObject_wpclsSetIcon
#define M_WPSac_wpclsObjectFromHandle M_WPObject_wpclsObjectFromHandle
#define M_WPSac_wpclsRemoveObjects M_WPObject_wpclsRemoveObjects
#define M_WPSac__get_somDataAlignment SOMClass__get_somDataAlignment
#define M_WPSac__get_somInstanceDataOffsets SOMClass__get_somInstanceDataOffsets
#define M_WPSac__get_somDirectInitClasses SOMClass__get_somDirectInitClasses
#define M_WPSac__set_somDirectInitClasses SOMClass__set_somDirectInitClasses
#define M_WPSac_somNew SOMClass_somNew
#define M_WPSac_somNewNoInit SOMClass_somNewNoInit
#define M_WPSac_somRenew SOMClass_somRenew
#define M_WPSac_somRenewNoInit SOMClass_somRenewNoInit
#define M_WPSac_somRenewNoZero SOMClass_somRenewNoZero
#define M_WPSac_somRenewNoInitNoZero SOMClass_somRenewNoInitNoZero
#define M_WPSac_somAllocate SOMClass_somAllocate
#define M_WPSac_somDeallocate SOMClass_somDeallocate
#define M_WPSac__get_somClassAllocate SOMClass__get_somClassAllocate
#define M_WPSac__get_somClassDeallocate SOMClass__get_somClassDeallocate
#define M_WPSac_somGetInstanceInitMask SOMClass_somGetInstanceInitMask
#define M_WPSac_somGetInstanceDestructionMask SOMClass_somGetInstanceDestructionMask
#define M_WPSac_somGetInstanceAssignmentMask SOMClass_somGetInstanceAssignmentMask
#define M_WPSac_somInitClass SOMClass_somInitClass
#define M_WPSac_somInitMIClass SOMClass_somInitMIClass
#define M_WPSac_somAddStaticMethod SOMClass_somAddStaticMethod
#define M_WPSac_somAddDynamicMethod SOMClass_somAddDynamicMethod
#define M_WPSac_somOverrideSMethod SOMClass_somOverrideSMethod
#define M_WPSac_somClassReady SOMClass_somClassReady
#define M_WPSac_somGetApplyStub SOMClass_somGetApplyStub
#define M_WPSac_somGetClassData SOMClass_somGetClassData
#define M_WPSac_somSetClassData SOMClass_somSetClassData
#define M_WPSac_somGetClassMtab SOMClass_somGetClassMtab
#define M_WPSac_somGetInstanceOffset SOMClass_somGetInstanceOffset
#define M_WPSac_somGetInstancePartSize SOMClass_somGetInstancePartSize
#define M_WPSac_somGetInstanceSize SOMClass_somGetInstanceSize
#define M_WPSac_somGetInstanceToken SOMClass_somGetInstanceToken
#define M_WPSac_somGetMemberToken SOMClass_somGetMemberToken
#define M_WPSac_somGetMethodData SOMClass_somGetMethodData
#define M_WPSac_somGetRdStub SOMClass_somGetRdStub
#define M_WPSac_somGetMethodDescriptor SOMClass_somGetMethodDescriptor
#define M_WPSac_somGetMethodIndex SOMClass_somGetMethodIndex
#define M_WPSac_somGetMethodToken SOMClass_somGetMethodToken
#define M_WPSac_somGetName SOMClass_somGetName
#define M_WPSac_somGetNthMethodData SOMClass_somGetNthMethodData
#define M_WPSac_somGetNthMethodInfo SOMClass_somGetNthMethodInfo
#define M_WPSac_somGetNumMethods SOMClass_somGetNumMethods
#define M_WPSac_somGetNumStaticMethods SOMClass_somGetNumStaticMethods
#define M_WPSac_somGetParent SOMClass_somGetParent
#define M_WPSac_somGetParents SOMClass_somGetParents
#define M_WPSac_somGetPClsMtab SOMClass_somGetPClsMtab
#define M_WPSac_somGetPClsMtabs SOMClass_somGetPClsMtabs
#define M_WPSac_somGetVersionNumbers SOMClass_somGetVersionNumbers
#define M_WPSac_somSetMethodDescriptor SOMClass_somSetMethodDescriptor
#define M_WPSac_somFindMethod SOMClass_somFindMethod
#define M_WPSac_somFindMethodOk SOMClass_somFindMethodOk
#define M_WPSac_somFindSMethod SOMClass_somFindSMethod
#define M_WPSac_somFindSMethodOk SOMClass_somFindSMethodOk
#define M_WPSac_somLookupMethod SOMClass_somLookupMethod
#define M_WPSac_somCheckVersion SOMClass_somCheckVersion
#define M_WPSac_somDescendedFrom SOMClass_somDescendedFrom
#define M_WPSac_somSupportsMethod SOMClass_somSupportsMethod
#define M_WPSac_somDefinedMethod SOMClass_somDefinedMethod
#define M_WPSac_somOverrideMtab SOMClass_somOverrideMtab
#define M_WPSac_somDefaultInit SOMObject_somDefaultInit
#define M_WPSac_somDestruct SOMObject_somDestruct
#define M_WPSac_somDefaultCopyInit SOMObject_somDefaultCopyInit
#define M_WPSac_somDefaultAssign SOMObject_somDefaultAssign
#define M_WPSac_somDefaultConstCopyInit SOMObject_somDefaultConstCopyInit
#define M_WPSac_somDefaultVCopyInit SOMObject_somDefaultVCopyInit
#define M_WPSac_somDefaultConstVCopyInit SOMObject_somDefaultConstVCopyInit
#define M_WPSac_somDefaultConstAssign SOMObject_somDefaultConstAssign
#define M_WPSac_somDefaultVAssign SOMObject_somDefaultVAssign
#define M_WPSac_somDefaultConstVAssign SOMObject_somDefaultConstVAssign
#define M_WPSac_somInit SOMObject_somInit
#define M_WPSac_somFree SOMObject_somFree
#define M_WPSac_somUninit SOMObject_somUninit
#define M_WPSac_somGetClass SOMObject_somGetClass
#define M_WPSac_somGetClassName SOMObject_somGetClassName
#define M_WPSac_somGetSize SOMObject_somGetSize
#define M_WPSac_somIsA SOMObject_somIsA
#define M_WPSac_somIsInstanceOf SOMObject_somIsInstanceOf
#define M_WPSac_somRespondsTo SOMObject_somRespondsTo
#define M_WPSac_somDispatch SOMObject_somDispatch
#define M_WPSac_somClassDispatch SOMObject_somClassDispatch
#define M_WPSac_somCastObj SOMObject_somCastObj
#define M_WPSac_somResetObj SOMObject_somResetObj
#define M_WPSac_somDispatchV SOMObject_somDispatchV
#define M_WPSac_somDispatchL SOMObject_somDispatchL
#define M_WPSac_somDispatchA SOMObject_somDispatchA
#define M_WPSac_somDispatchD SOMObject_somDispatchD
#define M_WPSac_somPrintSelf SOMObject_somPrintSelf
#define M_WPSac_somDumpSelf SOMObject_somDumpSelf
#define M_WPSac_somDumpSelfInt SOMObject_somDumpSelfInt
#endif /* SOM_DONT_USE_INHERITED_MACROS */

#endif       /* SOM_M_WPSac_h */
