.*----------------------------------------------------------
.* Sammy -- Workplace Shell Administration
.*
.* IPF Help File
.*
.*----------------------------------------------------------

:userdoc. 

.*----------------------------------------------------------
.*  Einloggen
.*      res = PANEL_LOGIN
.*----------------------------------------------------------
:h1 res=20 id=idSam.LOGIN

:p.Start a session by entering a valid password and name.
If a magnetic card reader is attached to your computer, that is compatible to
IBM's standard interface (MAGCALLS.DLL), you may also use an identification card.

:p.If logon is successful, the system will start your associated workplace shell
and also attach you to your LAN-ids, if configured.

:euserdoc.

