.*----------------------------------------------------------
.* Sammy -- Workplace Shell Administration
.*
.* IPF Help File
.*
.*----------------------------------------------------------

:userdoc. 

.*----------------------------------------------------------
.*  Einloggen
.*      res = PANEL_LOGIN
.*----------------------------------------------------------
:h1 res=1000 id=idSam.Anmelden
:p.Eine Sitzung kann durch die Eingabe eines gltigen Namens und Kennwortes
gestartet werden.
Falls ein Magnetkartenleser angeschlossen ist, der ber das IBM Standard-Interface
verfgt (MAGCALLS.DLL), kann auch eine Identifikationskarte verwendet werden.

:p.Ist der Anmeldevorgang erfolgreich, startet das System die zugeh”rige
Arbeitsoberfl„che und - falls vom Administrator so konfiguriert -
nimmt es die notwendigen Anmeldungen fr lokale Netzwerke vor.

:h1 res=1002 id=idOpt.Optionen
:p.Dieser Knopf ”ffnet das Optionenmen.

:h1 res=1003 id=idSD.Systemabschluá
:p.Von hier aus kann ein Systemabschluá des Rechners durchgefhrt werden,
ohne daá vorher ein Anmeldevorgang fr eine Benutzer-ID notwendig ist.

:h1 res=1004 id=idPwd.Kennwort „ndern
:p.Dieser Menpunkt ”ffnet eine Dialogbox, die das ndern von
Benutzer-Kennw”rtern gestattet.

:h1 res=1010 id=idEdit.Kennwort „ndern
:p.In dieser Dialogbox kann das Kennwort einzelner Benutzer ge„ndert werden.
Dazu muá das aktuell gltige Kennwort dieses Benutzers bekannt sein.

:h1 res=1011 id=idUser.Benutzername
:p.Hier den Namen des Benutzers eingeben.

:h1 res=1012 id=idOldPwd.Altes Kennwort
:p.Hier das aktuell gltige Kennwort des Benutzers eingeben.
Falls bisher fr diesen Benutzer keines erforderlich war, diese Zeile
leer lassen.

:p.Das Kennwort wird nicht angezeigt.

:h1 res=1013 id=idPassword.Neues Kennwort
:p.Hier das neue Kennwort eingeben.
Soll das Kennwort gel”scht werden, diese Zeile leer lassen.

:p.Das Kennwort wird nicht angezeigt.

:h1 res=1014 id=idVerify.Neues Kennwort berprfen
:p.Hier dasselbe Kennwort wie in der Zeile vorher zur šberprfung eingeben.

:p.Das Kennwort wird nicht angezeigt.


:h1 res=1005 id=idView.Ansicht einstellen
:p.Hier kann die Hintergrundfarbe sowie das Hintergrundbild fr das 
Sammy-Hauptfenster ausgew„hlt werden.
:p.Als Hintergrundbild kann jede Bitmapdatei im OS/2
oder Windows-Format oder eine OS/2 Bitmaparraydatei verwendet werden.

:h1 res=1015 id=idValue.Farbauswahl
:p.Dieser Wertebereich zeigt die zur Auswahl stehende Farbpalette.

:h1 res=1016 id=idPath.Hintergrundbildauswahl
:p.In dieses Eingabefeld kann der Pfad eines Hintergrundbildes eingegeben werden.    


:h1 res=1017 id=idSearch. Hintergrundbild suchen
:p.Ein Druck auf diesen Knopf ”ffnet den Suchdialog fr ein Hintergrundbild.   

:euserdoc.

