  WPSac - Workplace Shell Access Control

WPSac is a program package, that prevents the OS/2 workplace shell from unauthorized access.
It serves for the following tasks:
1) A logon panel for different users / user groups
2) Protection of the objects on the individual workplace shells
3) "Single signon feature" to logon to other products during the starting of a desktop

(C) noller & breining software, 1995...1999