/*  FÅr die Logon bzw. Logoff-Prozeduren werden           */
/*  folgende Variablen bereits vom System vorbelegt.      */
/*                                                        */
/*  USERNAME       Name des Benutzers fÅr An- bzw.        */
/*                 Abmeldung                              */
/*                                                        */
/*  PASSWORD       Passwort des Benutzers fÅr die         */
/*                 Anmeldung                              */
/*                                                        */
/*  DOMAIN         Weitere Logon-Information z.B. Domain  */
/*                 oder Servername                        */
/*                                                        */
/*  WPSAC_USERNAME Name des OS/2-Benutzers                */
