  WPSac - Workplace Shell Access Control

WPSac ist ein Programmpaket, das die Arbeitsoberfl„che von OS/2 vor unbefugtem Zugriff schtzt.
Es erfllt die folgenden Aufgaben:
1) Einwahldialog fr verschiedene Benutzer(gruppen)
2) Schutz von Objekten auf den jeweiligen Arbeitsoberfl„chen
3) "Single-Signon-F„higkeit" zur Anmeldung an anderen Produkten w„hrend des Starts einer Oberfl„che

(C) noller & breining software, 1995...1999