/* A lexical scanner generated by flex */

/* Scanner skeleton version:
 * $Header: /home/daffy/u0/vern/flex/RCS/flex.skl,v 2.47 93/12/11 10:56:41 vern Exp $
 */

#define FLEX_SCANNER

#include <stdio.h>


/* cfront 1.2 defines "c_plusplus" instead of "__cplusplus" */
#ifdef c_plusplus
#ifndef __cplusplus
#define __cplusplus
#endif
#endif


#ifdef __cplusplus

#include <stdlib.h>
#include <unistd.h>

/* Use prototypes in function declarations. */
#define YY_USE_PROTOS

/* The "const" storage-class-modifier is valid. */
#define YY_USE_CONST

#else	/* ! __cplusplus */

#ifdef __STDC__

#define YY_USE_PROTOS
#define YY_USE_CONST

#endif	/* __STDC__ */
#endif	/* ! __cplusplus */


#ifdef __TURBOC__
#define YY_USE_CONST
#endif


#ifndef YY_USE_CONST
#ifndef const
#define const
#endif
#endif


#ifdef YY_USE_PROTOS
#define YY_PROTO(proto) proto
#else
#define YY_PROTO(proto) ()
#endif

/* Returned upon end-of-file. */
#define YY_NULL 0

/* Promotes a possibly negative, possibly signed char to an unsigned
 * integer for use as an array index.  If the signed char is negative,
 * we want to instead treat it as an 8-bit unsigned char, hence the
 * double cast.
 */
#define YY_SC_TO_UI(c) ((unsigned int) (unsigned char) c)

/* Enter a start condition.  This macro really ought to take a parameter,
 * but we do it the disgusting crufty way forced on us by the ()-less
 * definition of BEGIN.
 */
#define BEGIN yy_start = 1 + 2 *

/* Translate the current start state into a value that can be later handed
 * to BEGIN to return to the state.
 */
#define YY_START ((yy_start - 1) / 2)

/* Action number for EOF rule of a given start state. */
#define YY_STATE_EOF(state) (YY_END_OF_BUFFER + state + 1)

/* Special action meaning "start processing a new file".  Now included
 * only for backward compatibility with previous versions of flex.
 */
#define YY_NEW_FILE yyrestart( yyin )

#define YY_END_OF_BUFFER_CHAR 0

/* Size of default input buffer. */
#define YY_BUF_SIZE 16384

typedef struct yy_buffer_state *YY_BUFFER_STATE;

extern int yyleng;
extern FILE *yyin, *yyout;

#ifdef __cplusplus
extern "C" {
#endif
	extern void *yy_flex_alloc YY_PROTO(( int ));
	extern void *yy_flex_realloc YY_PROTO(( void *ptr, int size ));
	extern void yy_flex_free YY_PROTO(( void * ));
	extern int yywrap YY_PROTO(( void ));
	extern void yy_strcpy YY_PROTO(( char *s1, const char *s2 ));
#ifdef __cplusplus
	}
#endif

#define EOB_ACT_CONTINUE_SCAN 0
#define EOB_ACT_END_OF_FILE 1
#define EOB_ACT_LAST_MATCH 2

/* The funky do-while in the following #define is used to turn the definition
 * int a single C statement (which needs a semi-colon terminator).  This
 * avoids problems with code like:
 *
 * 	if ( condition_holds )
 *		yyless( 5 );
 *	else
 *		do_something_else();
 *
 * Prior to using the do-while the compiler would get upset at the
 * "else" because it interpreted the "if" statement as being all
 * done when it reached the ';' after the yyless() call.
 */

/* Return all but the first 'n' matched characters back to the input stream. */

#define yyless(n) \
	do \
		{ \
		/* Undo effects of setting up yytext. */ \
		*yy_cp = yy_hold_char; \
		yy_c_buf_p = yy_cp = yy_bp + n - YY_MORE_ADJ; \
		YY_DO_BEFORE_ACTION; /* set up yytext again */ \
		} \
	while ( 0 )

#define unput(c) yyunput( c, yytext_ptr )


struct yy_buffer_state
	{
	FILE *yy_input_file;

	char *yy_ch_buf;		/* input buffer */
	char *yy_buf_pos;		/* current position in input buffer */

	/* Size of input buffer in bytes, not including room for EOB
	 * characters.
	 */
	int yy_buf_size;

	/* Number of characters read into yy_ch_buf, not including EOB
	 * characters.
	 */
	int yy_n_chars;

	/* Whether this is an "interactive" input source; if so, and
	 * if we're using stdio for input, then we want to use getc()
	 * instead of fread(), to make sure we stop fetching input after
	 * each newline.
	 */
	int yy_is_interactive;

	/* Whether to try to fill the input buffer when we reach the
	 * end of it.
	 */
	int yy_fill_buffer;

	/* Whether we've seen an EOF on this buffer. */
	int yy_eof_status;
#define EOF_NOT_SEEN 0
	/* "Pending" happens when the EOF has been seen but there's still
	 * some text to process.  Note that when we actually see the EOF,
	 * we switch the status back to "not seen" (via yyrestart()), so
	 * that the user can continue scanning by just pointing yyin at
	 * a new input file.
	 */
#define EOF_PENDING 1
	};

static YY_BUFFER_STATE yy_current_buffer = 0;

/* We provide macros for accessing buffer states in case in the
 * future we want to put the buffer states in a more general
 * "scanner state".
 */
#define YY_CURRENT_BUFFER yy_current_buffer


/* yy_hold_char holds the character lost when yytext is formed. */
static char yy_hold_char;

static int yy_n_chars;		/* number of characters read into yy_ch_buf */


int yyleng;

/* Points to current character in buffer. */
static char *yy_c_buf_p = (char *) 0;
static int yy_init = 1;		/* whether we need to initialize */
static int yy_start = 0;	/* start state number */

/* Flag which is used to allow yywrap()'s to do buffer switches
 * instead of setting up a fresh yyin.  A bit of a hack ...
 */
static int yy_did_buffer_switch_on_eof;

static void yyunput YY_PROTO(( int c, char *buf_ptr ));
void yyrestart YY_PROTO(( FILE *input_file ));
void yy_switch_to_buffer YY_PROTO(( YY_BUFFER_STATE new_buffer ));
void yy_load_buffer_state YY_PROTO(( void ));
YY_BUFFER_STATE yy_create_buffer YY_PROTO(( FILE *file, int size ));
void yy_delete_buffer YY_PROTO(( YY_BUFFER_STATE b ));
void yy_init_buffer YY_PROTO(( YY_BUFFER_STATE b, FILE *file ));

#define yy_new_buffer yy_create_buffer

#define INITIAL 0
typedef unsigned char YY_CHAR;
typedef int yy_state_type;

#define YY_USES_REJECT
FILE *yyin = NULL, *yyout = NULL;
extern int yylineno;
int yylineno = 1;
extern char yytext[];


#ifdef __cplusplus
static int yyinput YY_PROTO(( void ));
#else
static int input YY_PROTO(( void ));
#endif

static yy_state_type yy_get_previous_state YY_PROTO(( void ));
static yy_state_type yy_try_NUL_trans YY_PROTO(( yy_state_type current_state ));
static int yy_get_next_buffer YY_PROTO(( void ));
static void yy_fatal_error YY_PROTO(( const char msg[] ));

/* Done after the current pattern has been matched and before the
 * corresponding action - sets up yytext.
 */
#define YY_DO_BEFORE_ACTION \
	yytext_ptr = yy_bp; \
	yytext_ptr -= yy_more_len; \
	yyleng = yy_cp - yytext_ptr; \
	yy_hold_char = *yy_cp; \
	*yy_cp = '\0'; \
	if ( yyleng >= YYLMAX ) \
		YY_FATAL_ERROR( "token too large, exceeds YYLMAX" ); \
	yy_strcpy( yytext, yytext_ptr ); \
	yy_c_buf_p = yy_cp;

#define YY_END_OF_BUFFER 74
static const short int yy_acclist[124] =
    {   0,
       74,   72,   73,   71,   72,   73,   71,   73,   72,   73,
       67,   72,   73,   68,   72,   73,   70,   72,   73,   69,
       72,   73,   72,   73,   72,   73,   72,   73,   72,   73,
       72,   73,   72,   73,   72,   73,   72,   73,   72,   73,
       72,   73,   72,   73,   72,   73,   72,   73,   72,   73,
       72,   73,   72,   73,   72,   73,   71,    8,   33,   13,
       23,   51,   41,   11,    9,   35,   57,    5,    3,   39,
       34,   21,    4,   19,   61,   14,   24,   52,   42,   12,
       10,   36,   58,    1,   29,   53,   37,   55,   40,   22,
       63,   43,   25,   65,    6,   45,   20,   62,   30,   54,

       38,    7,   27,   59,   17,   47,    2,   56,   64,   44,
       66,   46,   28,   60,   18,   48,   26,   15,   49,   31,
       16,   50,   32
    } ;

static const short int yy_accept[392] =
    {   0,
        1,    1,    1,    2,    4,    7,    9,   11,   14,   17,
       20,   23,   25,   27,   29,   31,   33,   35,   37,   39,
       41,   43,   45,   47,   49,   51,   53,   55,   57,   58,
       58,   59,   59,   59,   59,   59,   59,   59,   59,   59,
       59,   59,   59,   59,   59,   59,   59,   59,   59,   59,
       59,   59,   59,   59,   59,   59,   59,   59,   59,   59,
       59,   59,   59,   59,   59,   59,   59,   59,   59,   59,
       59,   59,   59,   59,   59,   59,   59,   59,   59,   59,
       60,   60,   60,   60,   60,   60,   60,   60,   60,   60,
       60,   60,   60,   60,   60,   60,   60,   60,   60,   60,

       60,   60,   60,   60,   60,   60,   60,   60,   60,   60,
       60,   60,   60,   60,   60,   60,   61,   61,   61,   61,
       61,   61,   61,   62,   62,   63,   64,   64,   65,   65,
       66,   66,   66,   66,   66,   66,   66,   66,   66,   66,
       66,   66,   66,   66,   66,   66,   66,   66,   66,   66,
       66,   66,   66,   66,   66,   66,   66,   67,   67,   67,
       67,   67,   67,   67,   67,   67,   68,   68,   68,   68,
       69,   69,   69,   69,   70,   71,   71,   71,   71,   71,
       71,   71,   71,   71,   71,   71,   71,   71,   71,   71,
       71,   71,   71,   71,   71,   71,   71,   71,   71,   71,

       72,   72,   72,   72,   72,   72,   72,   72,   72,   72,
       72,   72,   72,   72,   72,   72,   72,   73,   73,   73,
       73,   73,   73,   73,   74,   74,   74,   74,   74,   74,
       74,   74,   74,   75,   75,   75,   75,   76,   76,   76,
       77,   77,   77,   77,   77,   77,   78,   79,   80,   80,
       81,   81,   82,   83,   83,   83,   83,   83,   83,   83,
       83,   84,   84,   84,   84,   84,   85,   85,   85,   85,
       86,   87,   87,   87,   87,   87,   87,   88,   89,   89,
       89,   89,   89,   89,   89,   89,   89,   90,   90,   90,
       90,   90,   90,   90,   90,   90,   91,   91,   91,   91,

       91,   91,   91,   91,   91,   91,   92,   92,   93,   93,
       93,   93,   93,   94,   94,   95,   95,   96,   96,   96,
       97,   97,   97,   97,   97,   98,   98,   98,   99,   99,
       99,  100,  101,  101,  101,  101,  101,  101,  102,  103,
      104,  105,  106,  107,  107,  107,  107,  108,  109,  109,
      109,  109,  109,  109,  110,  111,  111,  111,  111,  111,
      111,  111,  111,  111,  111,  112,  112,  112,  113,  114,
      115,  116,  117,  118,  118,  119,  120,  120,  120,  120,
      120,  120,  120,  120,  121,  121,  122,  123,  123,  124,
      124

    } ;

static const int yy_ec[256] =
    {   0,
        1,    1,    1,    1,    1,    1,    1,    1,    2,    3,
        1,    1,    1,    1,    1,    1,    1,    1,    1,    1,
        1,    1,    1,    1,    1,    2,    1,    1,    1,    1,
        1,    2,    1,    4,    1,    1,    1,    1,    1,    5,
        6,    1,    1,    7,    1,    1,    1,    1,    1,    1,
        1,    1,    1,    1,    1,    1,    1,    1,    1,    1,
        8,    1,    1,    1,    9,   10,   11,   12,   13,   14,
       15,   16,   17,   18,   19,   20,   21,   22,   23,   24,
        1,   25,   26,   27,   28,   29,   30,    1,   31,    1,
        1,    1,    1,    1,    1,    1,    1,    1,    1,    1,

        1,    1,    1,    1,    1,    1,    1,    1,    1,    1,
        1,    1,    1,    1,    1,    1,    1,    1,    1,    1,
        1,    1,    1,    1,    1,    1,    1,    1,    1,    1,
        1,    1,    1,    1,    1,    1,    1,    1,    1,    1,
        1,    1,    1,    1,    1,    1,    1,    1,    1,    1,
        1,    1,    1,    1,    1,    1,    1,    1,    1,    1,
        1,    1,    1,    1,    1,    1,    1,    1,    1,    1,
        1,    1,    1,    1,    1,    1,    1,    1,    1,    1,
        1,    1,    1,    1,    1,    1,    1,    1,    1,    1,
        1,    1,    1,    1,    1,    1,    1,    1,    1,    1,

        1,    1,    1,    1,    1,    1,    1,    1,    1,    1,
        1,    1,    1,    1,    1,    1,    1,    1,    1,    1,
        1,    1,    1,    1,    1,    1,    1,    1,    1,    1,
        1,    1,    1,    1,    1,    1,    1,    1,    1,    1,
        1,    1,    1,    1,    1,    1,    1,    1,    1,    1,
        1,    1,    1,    1,    1
    } ;

static const int yy_meta[32] =
    {   0,
        1,    1,    2,    1,    1,    1,    1,    1,    1,    1,
        1,    1,    1,    1,    1,    1,    1,    1,    1,    1,
        1,    1,    1,    1,    1,    1,    1,    1,    1,    1,
        1
    } ;

static const short int yy_base[392] =
    {   0,
        0,    0,  399,  400,   30,   32,  394,  400,  400,  400,
      400,  372,   16,   27,  374,  378,  381,  382,   21,  369,
       30,   32,   38,  378,   32,   33,  373,  372,   57,  384,
      400,  362,   42,  362,  372,  364,   47,  374,  370,  359,
      360,  356,  356,  366,  347,  345,   66,  356,  360,  352,
      340,   45,  348,   46,  341,  343,  346,  339,  352,  340,
      337,  340,  352,  334,  333,  327,  348,  337,   67,  342,
      345,  338,  329,  339,  326,  327,  329,  328,  333,  400,
      320,   75,   59,  327,  330,  331,   62,  318,  327,  315,
       72,  325,   86,   88,  320,  323,  313,  321,  307,  310,

      316,  321,  316,  301,  300,  299,  301,  304,  310,  309,
      304,  308,  297,  292,  304,  400,  289,  295,  286,  296,
      285,  294,  400,  300,  400,  400,  280,  400,  280,  400,
      282,  283,  281,  291,  283,   91,  293,  279,  280,  276,
      276,  286,  267,  265,  281,  273,   87,  270,   87,  263,
      265,  268,  275,  270,  264,  274,  400,  257,  261,  255,
      256,  259,  268,  261,  265,  400,  256,  262,  245,  400,
      263,  249,  256,  400,  400,  257,  252,  248,  240,  253,
      245,  246,  246,  238,  252,  234,  228,  249,  238,  247,
      242,  245,  238,  240,  227,  228,  230,  229,  234,  400,

      224,  232,  222,  228,  233,  228,  213,  212,  211,  213,
      223,  209,  222,  206,  205,  222,  400,  221,  216,  201,
      205,  203,  216,  400,  207,  203,  192,  208,  211,  208,
      191,  197,  400,  190,  202,  201,  400,  191,  199,  400,
      184,  190,  181,  181,  190,  400,  400,  400,  177,  400,
      177,  400,  400,  177,  176,  177,  180,  189,  182,  186,
      400,  177,  167,  178,  171,  400,  180,  171,  170,  400,
      400,  175,  159,  161,  174,  173,  400,  400,  163,  165,
      166,  169,  152,  169,  149,  163,  400,  164,  159,  155,
      161,  153,  155,  147,  143,  400,  160,  155,  140,  144,

      142,  155,  146,  152,  131,  400,  147,  400,  133,  136,
      144,  126,  400,  132,  400,  143,  400,  136,  125,  400,
      138,  141,  138,  121,  400,  121,  133,  400,  132,  123,
      400,  400,  128,  112,  114,  127,  119,  400,  400,  400,
      400,  400,  400,  111,  114,  123,  400,  400,  113,  115,
      116,  103,  101,  400,  400,  104,  107,  115,   97,  113,
      109,  102,   93,   99,  400,  110,  103,  400,  400,  400,
      400,  400,  400,  106,  400,  400,   89,   92,   99,   83,
       90,   81,   41,  400,   57,  400,  400,   32,  400,  400,
       48

    } ;

static const short int yy_def[392] =
    {   0,
      390,    1,  390,  390,  390,  390,  391,  390,  390,  390,
      390,  390,  390,  390,  390,  390,  390,  390,  390,  390,
      390,  390,  390,  390,  390,  390,  390,  390,  390,  391,
      390,  390,  390,  390,  390,  390,  390,  390,  390,  390,
      390,  390,  390,  390,  390,  390,  390,  390,  390,  390,
      390,  390,  390,  390,  390,  390,  390,  390,  390,  390,
      390,  390,  390,  390,  390,  390,  390,  390,  390,  390,
      390,  390,  390,  390,  390,  390,  390,  390,  390,  390,
      390,  390,  390,  390,  390,  390,  390,  390,  390,  390,
      390,  390,  390,  390,  390,  390,  390,  390,  390,  390,

      390,  390,  390,  390,  390,  390,  390,  390,  390,  390,
      390,  390,  390,  390,  390,  390,  390,  390,  390,  390,
      390,  390,  390,  390,  390,  390,  390,  390,  390,  390,
      390,  390,  390,  390,  390,  390,  390,  390,  390,  390,
      390,  390,  390,  390,  390,  390,  390,  390,  390,  390,
      390,  390,  390,  390,  390,  390,  390,  390,  390,  390,
      390,  390,  390,  390,  390,  390,  390,  390,  390,  390,
      390,  390,  390,  390,  390,  390,  390,  390,  390,  390,
      390,  390,  390,  390,  390,  390,  390,  390,  390,  390,
      390,  390,  390,  390,  390,  390,  390,  390,  390,  390,

      390,  390,  390,  390,  390,  390,  390,  390,  390,  390,
      390,  390,  390,  390,  390,  390,  390,  390,  390,  390,
      390,  390,  390,  390,  390,  390,  390,  390,  390,  390,
      390,  390,  390,  390,  390,  390,  390,  390,  390,  390,
      390,  390,  390,  390,  390,  390,  390,  390,  390,  390,
      390,  390,  390,  390,  390,  390,  390,  390,  390,  390,
      390,  390,  390,  390,  390,  390,  390,  390,  390,  390,
      390,  390,  390,  390,  390,  390,  390,  390,  390,  390,
      390,  390,  390,  390,  390,  390,  390,  390,  390,  390,
      390,  390,  390,  390,  390,  390,  390,  390,  390,  390,

      390,  390,  390,  390,  390,  390,  390,  390,  390,  390,
      390,  390,  390,  390,  390,  390,  390,  390,  390,  390,
      390,  390,  390,  390,  390,  390,  390,  390,  390,  390,
      390,  390,  390,  390,  390,  390,  390,  390,  390,  390,
      390,  390,  390,  390,  390,  390,  390,  390,  390,  390,
      390,  390,  390,  390,  390,  390,  390,  390,  390,  390,
      390,  390,  390,  390,  390,  390,  390,  390,  390,  390,
      390,  390,  390,  390,  390,  390,  390,  390,  390,  390,
      390,  390,  390,  390,  390,  390,  390,  390,  390,    0,
      390

    } ;

static const short int yy_nxt[432] =
    {   0,
        4,    5,    6,    7,    8,    9,   10,   11,   12,    4,
       13,   14,   15,   16,    4,   17,   18,    4,    4,   19,
       20,   21,   22,   23,   24,   25,   26,    4,   27,   28,
        4,   29,   29,   29,   29,   33,   36,   43,   34,   37,
       35,   48,   46,   44,   54,   57,   50,   55,   30,   58,
       64,   38,   47,   51,   56,   49,  389,   59,   29,   29,
       69,  100,   52,   60,   65,  103,   70,  101,  135,  388,
      387,  136,  104,   71,   81,  119,   82,   83,  141,   84,
      146,   85,   86,  137,  142,   87,   88,   89,   90,   91,
       92,   93,   94,  120,  132,   95,  147,  133,  149,  134,

      152,  150,  386,  203,  190,  385,  206,  384,  151,  204,
      191,  383,  153,  207,  382,  381,  154,  192,  380,  379,
      378,  377,  376,  375,  374,  373,  372,  371,  370,  369,
      368,  367,  366,  365,  364,  363,  362,  361,  360,  359,
      358,  357,  356,  355,  354,  353,  352,  351,  350,  349,
      348,  347,  346,  345,  344,  343,  342,  341,  340,  339,
      338,  337,  336,  335,  334,  333,  332,  331,  330,  329,
      328,  327,  326,  325,  324,  323,  322,  321,  320,  319,
      318,  317,  316,  315,  314,  313,  312,  311,  310,  309,
      308,  307,  306,  305,  304,  303,  302,  301,  300,  299,

      298,  297,  296,  295,  294,  293,  292,  291,  290,  289,
      288,  287,  286,  285,  284,  283,  282,  281,  280,  279,
      278,  277,  276,  275,  274,  273,  272,  271,  270,  269,
      268,  267,  266,  265,  264,  263,  262,  261,  260,  259,
      258,  257,  256,  255,  254,  253,  252,  251,  250,  249,
      248,  247,  246,  245,  244,  243,  242,  241,  240,  239,
      238,  237,  236,  235,  234,  233,  232,  231,  230,  229,
      228,  227,  226,  225,  224,  223,  222,  221,  220,  219,
      218,  217,  216,  215,  214,  213,  212,  211,  210,  209,
      208,  205,  202,  201,  200,  199,  198,  197,  196,  195,

      194,  193,  189,  188,  187,  186,  185,  184,  183,  182,
      181,  180,  179,  178,  177,  176,  175,  174,  173,  172,
      171,  170,  169,  168,  167,  166,  165,  164,  163,  162,
      161,  160,  159,  158,  157,  156,  155,  148,  145,  144,
      143,  140,  139,  138,  131,  130,  129,  128,  127,  126,
      125,  124,  123,  122,  121,  118,  117,  116,  115,  114,
      113,  112,  111,  110,  109,  108,  107,  106,  105,  102,
       99,   98,   97,   96,   80,   79,   78,   77,   76,   75,
       74,   73,   72,   68,   67,   66,   63,   31,   62,   61,
       53,   45,   42,   41,   40,   39,   32,   31,  390,    3,

      390,  390,  390,  390,  390,  390,  390,  390,  390,  390,
      390,  390,  390,  390,  390,  390,  390,  390,  390,  390,
      390,  390,  390,  390,  390,  390,  390,  390,  390,  390,
      390
    } ;

static const short int yy_chk[432] =
    {   0,
        1,    1,    1,    1,    1,    1,    1,    1,    1,    1,
        1,    1,    1,    1,    1,    1,    1,    1,    1,    1,
        1,    1,    1,    1,    1,    1,    1,    1,    1,    1,
        1,    5,    5,    6,    6,   13,   14,   19,   13,   14,
       13,   22,   21,   19,   25,   26,   23,   25,  391,   26,
       33,   14,   21,   23,   25,   22,  388,   26,   29,   29,
       37,   52,   23,   26,   33,   54,   37,   52,   83,  385,
      383,   83,   54,   37,   47,   69,   47,   47,   87,   47,
       91,   47,   47,   83,   87,   47,   47,   47,   47,   47,
       47,   47,   47,   69,   82,   47,   91,   82,   93,   82,

       94,   93,  382,  147,  136,  381,  149,  380,   93,  147,
      136,  379,   94,  149,  378,  377,   94,  136,  374,  367,
      366,  364,  363,  362,  361,  360,  359,  358,  357,  356,
      353,  352,  351,  350,  349,  346,  345,  344,  337,  336,
      335,  334,  333,  330,  329,  327,  326,  324,  323,  322,
      321,  319,  318,  316,  314,  312,  311,  310,  309,  307,
      305,  304,  303,  302,  301,  300,  299,  298,  297,  295,
      294,  293,  292,  291,  290,  289,  288,  286,  285,  284,
      283,  282,  281,  280,  279,  276,  275,  274,  273,  272,
      269,  268,  267,  265,  264,  263,  262,  260,  259,  258,

      257,  256,  255,  254,  251,  249,  245,  244,  243,  242,
      241,  239,  238,  236,  235,  234,  232,  231,  230,  229,
      228,  227,  226,  225,  223,  222,  221,  220,  219,  218,
      216,  215,  214,  213,  212,  211,  210,  209,  208,  207,
      206,  205,  204,  203,  202,  201,  199,  198,  197,  196,
      195,  194,  193,  192,  191,  190,  189,  188,  187,  186,
      185,  184,  183,  182,  181,  180,  179,  178,  177,  176,
      173,  172,  171,  169,  168,  167,  165,  164,  163,  162,
      161,  160,  159,  158,  156,  155,  154,  153,  152,  151,
      150,  148,  146,  145,  144,  143,  142,  141,  140,  139,

      138,  137,  135,  134,  133,  132,  131,  129,  127,  124,
      122,  121,  120,  119,  118,  117,  115,  114,  113,  112,
      111,  110,  109,  108,  107,  106,  105,  104,  103,  102,
      101,  100,   99,   98,   97,   96,   95,   92,   90,   89,
       88,   86,   85,   84,   81,   79,   78,   77,   76,   75,
       74,   73,   72,   71,   70,   68,   67,   66,   65,   64,
       63,   62,   61,   60,   59,   58,   57,   56,   55,   53,
       51,   50,   49,   48,   46,   45,   44,   43,   42,   41,
       40,   39,   38,   36,   35,   34,   32,   30,   28,   27,
       24,   20,   18,   17,   16,   15,   12,    7,    3,  390,

      390,  390,  390,  390,  390,  390,  390,  390,  390,  390,
      390,  390,  390,  390,  390,  390,  390,  390,  390,  390,
      390,  390,  390,  390,  390,  390,  390,  390,  390,  390,
      390
    } ;

static yy_state_type yy_state_buf[YY_BUF_SIZE + 2], *yy_state_ptr;
static char *yy_full_match;
static int yy_lp;
#define REJECT \
{ \
*yy_cp = yy_hold_char; /* undo effects of setting up yytext */ \
yy_cp = yy_full_match; /* restore poss. backed-over text */ \
++yy_lp; \
goto find_rule; \
}
static int yy_more_flag = 0;
static int yy_more_len = 0;
#define yymore() (yy_more_flag = 1)
#define YY_MORE_ADJ yy_more_len
#ifndef YYLMAX
#define YYLMAX 8192
#endif

char yytext[YYLMAX];
char *yytext_ptr;
# line 1 "lexpars.l"
# line 2 "lexpars.l"
#include "y.tab.h"
char *MyString(char *pchIn);

/* Macros after this point can all be overridden by user definitions in
 * section 1.
 */

/* Amount of stuff to slurp up with each read. */
#ifndef YY_READ_BUF_SIZE
#define YY_READ_BUF_SIZE 8192
#endif

/* Copy whatever the last rule matched to the standard output. */

#ifndef ECHO
/* This used to be an fputs(), but since the string might contain NUL's,
 * we now use fwrite().
 */
#define ECHO (void) fwrite( yytext, yyleng, 1, yyout )
#endif

/* Gets input and stuffs it into "buf".  number of characters read, or YY_NULL,
 * is returned in "result".
 */
#ifndef YY_INPUT
#define YY_INPUT(buf,result,max_size) \
	if ( yy_current_buffer->yy_is_interactive ) \
		{ \
		int c = getc( yyin ); \
		result = c == EOF ? 0 : 1; \
		buf[0] = (char) c; \
		} \
	else if ( ((result = fread( buf, 1, max_size, yyin )) == 0) \
		  && ferror( yyin ) ) \
		YY_FATAL_ERROR( "input in flex scanner failed" );
#endif

/* No semi-colon after return; correct usage is to write "yyterminate();" -
 * we don't want an extra ';' after the "return" because that will cause
 * some compilers to complain about unreachable statements.
 */
#ifndef yyterminate
#define yyterminate() return YY_NULL
#endif

/* Report a fatal error. */
#ifndef YY_FATAL_ERROR
#define YY_FATAL_ERROR(msg) yy_fatal_error( msg )
#endif

/* Default declaration of generated scanner - a define so the user can
 * easily add parameters.
 */
#ifndef YY_DECL
#define YY_DECL int yylex YY_PROTO(( void ))
#endif

/* Code executed at the beginning of each rule, after yytext and yyleng
 * have been set up.
 */
#ifndef YY_USER_ACTION
#define YY_USER_ACTION
#endif

/* Code executed at the end of each rule. */
#ifndef YY_BREAK
#define YY_BREAK break;
#endif

YY_DECL
	{
	register yy_state_type yy_current_state;
	register char *yy_cp, *yy_bp;
	register int yy_act;

# line 5 "lexpars.l"


	if ( yy_init )
		{
#ifdef YY_USER_INIT
		YY_USER_INIT;
#endif

		if ( ! yy_start )
			yy_start = 1;	/* first start state */

		if ( ! yyin )
			yyin = stdin;

		if ( ! yyout )
			yyout = stdout;

		if ( yy_current_buffer )
			yy_init_buffer( yy_current_buffer, yyin );
		else
			yy_current_buffer =
				yy_create_buffer( yyin, YY_BUF_SIZE );

		yy_load_buffer_state();

		yy_init = 0;
		}

	while ( 1 )		/* loops until end-of-file is reached */
		{
		yy_more_len = 0;
		if ( yy_more_flag )
			{
			yy_more_len = yyleng;
			yy_more_flag = 0;
			}
		yy_cp = yy_c_buf_p;

		/* Support of yytext. */
		*yy_cp = yy_hold_char;

		/* yy_bp points to the position in yy_ch_buf of the start of
		 * the current run.
		 */
		yy_bp = yy_cp;

		yy_current_state = yy_start;
		yy_state_ptr = yy_state_buf;
		*yy_state_ptr++ = yy_current_state;
yy_match:
		do
			{
			register YY_CHAR yy_c = yy_ec[YY_SC_TO_UI(*yy_cp)];
			while ( yy_chk[yy_base[yy_current_state] + yy_c] != yy_current_state )
				{
				yy_current_state = (int) yy_def[yy_current_state];
				if ( yy_current_state >= 391 )
					yy_c = yy_meta[(unsigned int) yy_c];
				}
			yy_current_state = yy_nxt[yy_base[yy_current_state] + (unsigned int) yy_c];
			*yy_state_ptr++ = yy_current_state;
			++yy_cp;
			}
		while ( yy_base[yy_current_state] != 400 );

yy_find_action:
		yy_current_state = *--yy_state_ptr;
		yy_lp = yy_accept[yy_current_state];
find_rule: /* we branch to this label when backing up */
		for ( ; ; ) /* until we find what rule we matched */
			{
			if ( yy_lp && yy_lp < yy_accept[yy_current_state + 1] )
				{
				yy_act = yy_acclist[yy_lp];
					{
					yy_full_match = yy_cp;
					break;
					}
				}
			--yy_cp;
			yy_current_state = *--yy_state_ptr;
			yy_lp = yy_accept[yy_current_state];
			}

		YY_DO_BEFORE_ACTION;

		if ( yy_act != YY_END_OF_BUFFER )
			{
			int yyl;
			for ( yyl = 0; yyl < yyleng; ++yyl )
				if ( yytext[yyl] == '\n' )
					++yylineno;
			}

do_action:	/* This label is used only to access EOF actions. */


		switch ( yy_act )
	{ /* beginning of action switch */
case 1:
YY_USER_ACTION
# line 6 "lexpars.l"
return OBJ_BEGIN ;
	YY_BREAK
case 2:
YY_USER_ACTION
# line 7 "lexpars.l"
return ENDOBJECT ;
	YY_BREAK
case 3:
YY_USER_ACTION
# line 8 "lexpars.l"
return OBJ_CLASS ;
	YY_BREAK
case 4:
YY_USER_ACTION
# line 9 "lexpars.l"
return OBJ_TITLE ;
	YY_BREAK
case 5:
YY_USER_ACTION
# line 10 "lexpars.l"
return OBJ_TYPE  ;
	YY_BREAK
case 6:
YY_USER_ACTION
# line 11 "lexpars.l"
return OBJ_DEFTITLE ;
	YY_BREAK
case 7:
YY_USER_ACTION
# line 12 "lexpars.l"
return OBJ_PHYSNAME ;
	YY_BREAK
case 8:
YY_USER_ACTION
# line 13 "lexpars.l"
{ MyString(yytext); return STRING ; } ;
	YY_BREAK
case 9:
YY_USER_ACTION
# line 14 "lexpars.l"
return MOVE ;
	YY_BREAK
case 10:
YY_USER_ACTION
# line 15 "lexpars.l"
return NOMOVE ;
	YY_BREAK
case 11:
YY_USER_ACTION
# line 16 "lexpars.l"
return LINK ;
	YY_BREAK
case 12:
YY_USER_ACTION
# line 17 "lexpars.l"
return NOLINK ;
	YY_BREAK
case 13:
YY_USER_ACTION
# line 18 "lexpars.l"
return COPY ;
	YY_BREAK
case 14:
YY_USER_ACTION
# line 19 "lexpars.l"
return NOCOPY ;
	YY_BREAK
case 15:
YY_USER_ACTION
# line 20 "lexpars.l"
return DEFAULTICON ;
	YY_BREAK
case 16:
YY_USER_ACTION
# line 21 "lexpars.l"
return NODEFAULTICON ;
	YY_BREAK
case 17:
YY_USER_ACTION
# line 22 "lexpars.l"
return TEMPLATE ;
	YY_BREAK
case 18:
YY_USER_ACTION
# line 23 "lexpars.l"
return NOTEMPLATE ;
	YY_BREAK
case 19:
YY_USER_ACTION
# line 24 "lexpars.l"
return DELETE ;
	YY_BREAK
case 20:
YY_USER_ACTION
# line 25 "lexpars.l"
return NODELETE ;
	YY_BREAK
case 21:
YY_USER_ACTION
# line 26 "lexpars.l"
return PRINT ;
	YY_BREAK
case 22:
YY_USER_ACTION
# line 27 "lexpars.l"
return NOPRINT ;
	YY_BREAK
case 23:
YY_USER_ACTION
# line 28 "lexpars.l"
return DRAG ;
	YY_BREAK
case 24:
YY_USER_ACTION
# line 29 "lexpars.l"
return NODRAG ;
	YY_BREAK
case 25:
YY_USER_ACTION
# line 30 "lexpars.l"
return VISIBLE ;
	YY_BREAK
case 26:
YY_USER_ACTION
# line 31 "lexpars.l"
return NOTVISIBLE ;
	YY_BREAK
case 27:
YY_USER_ACTION
# line 32 "lexpars.l"
return SETTINGS ;
	YY_BREAK
case 28:
YY_USER_ACTION
# line 33 "lexpars.l"
return NOSETTINGS ;
	YY_BREAK
case 29:
YY_USER_ACTION
# line 34 "lexpars.l"
return RENAME ;
	YY_BREAK
case 30:
YY_USER_ACTION
# line 35 "lexpars.l"
return NORENAME ;
	YY_BREAK
case 31:
YY_USER_ACTION
# line 36 "lexpars.l"
return CREATEANOTHER ;
	YY_BREAK
case 32:
YY_USER_ACTION
# line 37 "lexpars.l"
return NOCREATEANOTHER ;
	YY_BREAK
case 33:
YY_USER_ACTION
# line 38 "lexpars.l"
return NEW ;
	YY_BREAK
case 34:
YY_USER_ACTION
# line 39 "lexpars.l"
return NONEW ;
	YY_BREAK
case 35:
YY_USER_ACTION
# line 40 "lexpars.l"
return OPEN ;
	YY_BREAK
case 36:
YY_USER_ACTION
# line 41 "lexpars.l"
return NOOPEN ;
	YY_BREAK
case 37:
YY_USER_ACTION
# line 42 "lexpars.l"
return WINDOW ;
	YY_BREAK
case 38:
YY_USER_ACTION
# line 43 "lexpars.l"
return NOWINDOW ;
	YY_BREAK
case 39:
YY_USER_ACTION
# line 44 "lexpars.l"
return CLOSE ;
	YY_BREAK
case 40:
YY_USER_ACTION
# line 45 "lexpars.l"
return NOCLOSE ;
	YY_BREAK
case 41:
YY_USER_ACTION
# line 46 "lexpars.l"
return HELP ;
	YY_BREAK
case 42:
YY_USER_ACTION
# line 47 "lexpars.l"
return NOHELP ;
	YY_BREAK
case 43:
YY_USER_ACTION
# line 48 "lexpars.l"
return PROGRAM ;
	YY_BREAK
case 44:
YY_USER_ACTION
# line 49 "lexpars.l"
return NOPROGRAM ;
	YY_BREAK
case 45:
YY_USER_ACTION
# line 50 "lexpars.l"
return ICONVIEW ;
	YY_BREAK
case 46:
YY_USER_ACTION
# line 51 "lexpars.l"
return NOICONVIEW ;
	YY_BREAK
case 47:
YY_USER_ACTION
# line 52 "lexpars.l"
return TREEVIEW ;
	YY_BREAK
case 48:
YY_USER_ACTION
# line 53 "lexpars.l"
return NOTREEVIEW ;
	YY_BREAK
case 49:
YY_USER_ACTION
# line 54 "lexpars.l"
return DETAILSVIEW ;
	YY_BREAK
case 50:
YY_USER_ACTION
# line 55 "lexpars.l"
return NODETAILSVIEW ;
	YY_BREAK
case 51:
YY_USER_ACTION
# line 56 "lexpars.l"
return FIND ;
	YY_BREAK
case 52:
YY_USER_ACTION
# line 57 "lexpars.l"
return NOFIND ;
	YY_BREAK
case 53:
YY_USER_ACTION
# line 58 "lexpars.l"
return SELECT ;
	YY_BREAK
case 54:
YY_USER_ACTION
# line 59 "lexpars.l"
return NOSELECT ;
	YY_BREAK
case 55:
YY_USER_ACTION
# line 60 "lexpars.l"
return ARRANGE ;
	YY_BREAK
case 56:
YY_USER_ACTION
# line 61 "lexpars.l"
return NOARRANGE ;
	YY_BREAK
case 57:
YY_USER_ACTION
# line 62 "lexpars.l"
return SORT ;
	YY_BREAK
case 58:
YY_USER_ACTION
# line 63 "lexpars.l"
return NOSORT ;
	YY_BREAK
case 59:
YY_USER_ACTION
# line 64 "lexpars.l"
return SHUTDOWN ;
	YY_BREAK
case 60:
YY_USER_ACTION
# line 65 "lexpars.l"
return NOSHUTDOWN ;
	YY_BREAK
case 61:
YY_USER_ACTION
# line 66 "lexpars.l"
return LOCKUP ;
	YY_BREAK
case 62:
YY_USER_ACTION
# line 67 "lexpars.l"
return NOLOCKUP ;
	YY_BREAK
case 63:
YY_USER_ACTION
# line 68 "lexpars.l"
return PALETTE ;
	YY_BREAK
case 64:
YY_USER_ACTION
# line 69 "lexpars.l"
return NOPALETTE ;
	YY_BREAK
case 65:
YY_USER_ACTION
# line 70 "lexpars.l"
return DBLKLICK ;
	YY_BREAK
case 66:
YY_USER_ACTION
# line 71 "lexpars.l"
return NODBLKLICK ;
	YY_BREAK
case 67:
YY_USER_ACTION
# line 72 "lexpars.l"
return '(';
	YY_BREAK
case 68:
YY_USER_ACTION
# line 73 "lexpars.l"
return ')';
	YY_BREAK
case 69:
YY_USER_ACTION
# line 74 "lexpars.l"
return '=';
	YY_BREAK
case 70:
YY_USER_ACTION
# line 75 "lexpars.l"
return ',';
	YY_BREAK
case 71:
YY_USER_ACTION
# line 76 "lexpars.l"
;
	YY_BREAK
case 72:
YY_USER_ACTION
# line 77 "lexpars.l"
return ERROR;
	YY_BREAK
case 73:
YY_USER_ACTION
# line 78 "lexpars.l"
ECHO;
	YY_BREAK
			case YY_STATE_EOF(INITIAL):
				yyterminate();

	case YY_END_OF_BUFFER:
		{
		/* Amount of text matched not including the EOB char. */
		int yy_amount_of_matched_text = yy_cp - yytext_ptr - 1;

		/* Undo the effects of YY_DO_BEFORE_ACTION. */
		*yy_cp = yy_hold_char;

		if ( yy_current_buffer->yy_input_file != yyin )
			{
			/* This can happen if we scan a file, yywrap() returns
			 * 1, and then later the user points yyin at a new
			 * file to resume scanning.  We have to assure
			 * consistency between yy_current_buffer and our
			 * globals.  Here is the right place to do so, because
			 * this is the first action (other than possibly a
			 * back-up) that will match for the new input file.
			 */
			yy_current_buffer->yy_input_file = yyin;
			yy_n_chars = yy_current_buffer->yy_n_chars;
			}

		/* Note that here we test for yy_c_buf_p "<=" to the position
		 * of the first EOB in the buffer, since yy_c_buf_p will
		 * already have been incremented past the NUL character
		 * (since all states make transitions on EOB to the
		 * end-of-buffer state).  Contrast this with the test
		 * in input().
		 */
		if ( yy_c_buf_p <= &yy_current_buffer->yy_ch_buf[yy_n_chars] )
			{ /* This was really a NUL. */
			yy_state_type yy_next_state;

			yy_c_buf_p = yytext_ptr + yy_amount_of_matched_text;

			yy_current_state = yy_get_previous_state();

			/* Okay, we're now positioned to make the NUL
			 * transition.  We couldn't have
			 * yy_get_previous_state() go ahead and do it
			 * for us because it doesn't know how to deal
			 * with the possibility of jamming (and we don't
			 * want to build jamming into it because then it
			 * will run more slowly).
			 */

			yy_next_state = yy_try_NUL_trans( yy_current_state );

			yy_bp = yytext_ptr + YY_MORE_ADJ;

			if ( yy_next_state )
				{
				/* Consume the NUL. */
				yy_cp = ++yy_c_buf_p;
				yy_current_state = yy_next_state;
				goto yy_match;
				}

			else
				{
				goto yy_find_action;
				}
			}

		else switch ( yy_get_next_buffer() )
			{
			case EOB_ACT_END_OF_FILE:
				{
				yy_did_buffer_switch_on_eof = 0;

				if ( yywrap() )
					{
					/* Note: because we've taken care in
					 * yy_get_next_buffer() to have set up
					 * yytext, we can now set up
					 * yy_c_buf_p so that if some total
					 * hoser (like flex itself) wants to
					 * call the scanner after we return the
					 * YY_NULL, it'll still work - another
					 * YY_NULL will get returned.
					 */
					yy_c_buf_p = yytext_ptr + YY_MORE_ADJ;

					yy_act = YY_STATE_EOF(YY_START);
					goto do_action;
					}

				else
					{
					if ( ! yy_did_buffer_switch_on_eof )
						YY_NEW_FILE;
					}
				break;
				}

			case EOB_ACT_CONTINUE_SCAN:
				yy_c_buf_p =
					yytext_ptr + yy_amount_of_matched_text;

				yy_current_state = yy_get_previous_state();

				yy_cp = yy_c_buf_p;
				yy_bp = yytext_ptr + YY_MORE_ADJ;
				goto yy_match;

			case EOB_ACT_LAST_MATCH:
				yy_c_buf_p =
				&yy_current_buffer->yy_ch_buf[yy_n_chars];

				yy_current_state = yy_get_previous_state();

				yy_cp = yy_c_buf_p;
				yy_bp = yytext_ptr + YY_MORE_ADJ;
				goto yy_find_action;
			}
		break;
		}

	default:
		YY_FATAL_ERROR(
			"fatal flex scanner internal error--no action found" );
	} /* end of action switch */
		} /* end of scanning one token */
	} /* end of yylex */


/* yy_get_next_buffer - try to read in a new buffer
 *
 * Returns a code representing an action:
 *	EOB_ACT_LAST_MATCH -
 *	EOB_ACT_CONTINUE_SCAN - continue scanning from current position
 *	EOB_ACT_END_OF_FILE - end of file
 */

static int yy_get_next_buffer()
	{
	register char *dest = yy_current_buffer->yy_ch_buf;
	register char *source = yytext_ptr - 1; /* copy prev. char, too */
	register int number_to_move, i;
	int ret_val;

	if ( yy_c_buf_p > &yy_current_buffer->yy_ch_buf[yy_n_chars + 1] )
		YY_FATAL_ERROR(
		"fatal flex scanner internal error--end of buffer missed" );

	if ( yy_current_buffer->yy_fill_buffer == 0 )
		{ /* Don't try to fill the buffer, so this is an EOF. */
		if ( yy_c_buf_p - yytext_ptr - YY_MORE_ADJ == 1 )
			{
			/* We matched a singled characater, the EOB, so
			 * treat this as a final EOF.
			 */
			return EOB_ACT_END_OF_FILE;
			}

		else
			{
			/* We matched some text prior to the EOB, first
			 * process it.
			 */
			return EOB_ACT_LAST_MATCH;
			}
		}

	/* Try to read more data. */

	/* First move last chars to start of buffer. */
	number_to_move = yy_c_buf_p - yytext_ptr;

	for ( i = 0; i < number_to_move; ++i )
		*(dest++) = *(source++);

	if ( yy_current_buffer->yy_eof_status != EOF_NOT_SEEN )
		/* don't do the read, it's not guaranteed to return an EOF,
		 * just force an EOF
		 */
		yy_n_chars = 0;

	else
		{
		int num_to_read =
			yy_current_buffer->yy_buf_size - number_to_move - 1;

		while ( num_to_read <= 0 )
			{ /* Not enough room in the buffer - grow it. */
#ifdef YY_USES_REJECT
			YY_FATAL_ERROR(
"input buffer overflow, can't enlarge buffer because scanner uses REJECT" );
#else

			/* just a shorter name for the current buffer */
			YY_BUFFER_STATE b = yy_current_buffer;

			int yy_c_buf_p_offset = yy_c_buf_p - b->yy_ch_buf;

			b->yy_buf_size *= 2;
			b->yy_ch_buf = (char *)
				yy_flex_realloc( (void *) b->yy_ch_buf,
						 b->yy_buf_size );

			if ( ! b->yy_ch_buf )
				YY_FATAL_ERROR(
				"fatal error - scanner input buffer overflow" );

			yy_c_buf_p = &b->yy_ch_buf[yy_c_buf_p_offset];

			num_to_read = yy_current_buffer->yy_buf_size -
						number_to_move - 1;
#endif
			}

		if ( num_to_read > YY_READ_BUF_SIZE )
			num_to_read = YY_READ_BUF_SIZE;

		/* Read in more data. */
		YY_INPUT( (&yy_current_buffer->yy_ch_buf[number_to_move]),
			yy_n_chars, num_to_read );
		}

	if ( yy_n_chars == 0 )
		{
		if ( number_to_move - YY_MORE_ADJ == 1 )
			{
			ret_val = EOB_ACT_END_OF_FILE;
			yyrestart( yyin );
			}

		else
			{
			ret_val = EOB_ACT_LAST_MATCH;
			yy_current_buffer->yy_eof_status = EOF_PENDING;
			}
		}

	else
		ret_val = EOB_ACT_CONTINUE_SCAN;

	yy_n_chars += number_to_move;
	yy_current_buffer->yy_ch_buf[yy_n_chars] = YY_END_OF_BUFFER_CHAR;
	yy_current_buffer->yy_ch_buf[yy_n_chars + 1] = YY_END_OF_BUFFER_CHAR;

	/* yytext begins at the second character in yy_ch_buf; the first
	 * character is the one which preceded it before reading in the latest
	 * buffer; it needs to be kept around in case it's a newline, so
	 * yy_get_previous_state() will have with '^' rules active.
	 */

	yytext_ptr = &yy_current_buffer->yy_ch_buf[1];

	return ret_val;
	}


/* yy_get_previous_state - get the state just before the EOB char was reached */

static yy_state_type yy_get_previous_state()
	{
	register yy_state_type yy_current_state;
	register char *yy_cp;

	yy_current_state = yy_start;
	yy_state_ptr = yy_state_buf;
	*yy_state_ptr++ = yy_current_state;

	for ( yy_cp = yytext_ptr + YY_MORE_ADJ; yy_cp < yy_c_buf_p; ++yy_cp )
		{
		register YY_CHAR yy_c = (*yy_cp ? yy_ec[YY_SC_TO_UI(*yy_cp)] : 1);
		while ( yy_chk[yy_base[yy_current_state] + yy_c] != yy_current_state )
			{
			yy_current_state = (int) yy_def[yy_current_state];
			if ( yy_current_state >= 391 )
				yy_c = yy_meta[(unsigned int) yy_c];
			}
		yy_current_state = yy_nxt[yy_base[yy_current_state] + (unsigned int) yy_c];
		*yy_state_ptr++ = yy_current_state;
		}

	return yy_current_state;
	}


/* yy_try_NUL_trans - try to make a transition on the NUL character
 *
 * synopsis
 *	next_state = yy_try_NUL_trans( current_state );
 */

#ifdef YY_USE_PROTOS
static yy_state_type yy_try_NUL_trans( yy_state_type yy_current_state )
#else
static yy_state_type yy_try_NUL_trans( yy_current_state )
yy_state_type yy_current_state;
#endif
	{
	register int yy_is_jam;

	register YY_CHAR yy_c = 1;
	while ( yy_chk[yy_base[yy_current_state] + yy_c] != yy_current_state )
		{
		yy_current_state = (int) yy_def[yy_current_state];
		if ( yy_current_state >= 391 )
			yy_c = yy_meta[(unsigned int) yy_c];
		}
	yy_current_state = yy_nxt[yy_base[yy_current_state] + (unsigned int) yy_c];
	*yy_state_ptr++ = yy_current_state;
	yy_is_jam = (yy_current_state == 390);

	return yy_is_jam ? 0 : yy_current_state;
	}


#ifdef YY_USE_PROTOS
static void yyunput( int c, register char *yy_bp )
#else
static void yyunput( c, yy_bp )
int c;
register char *yy_bp;
#endif
	{
	register char *yy_cp = yy_c_buf_p;

	/* undo effects of setting up yytext */
	*yy_cp = yy_hold_char;

	if ( yy_cp < yy_current_buffer->yy_ch_buf + 2 )
		{ /* need to shift things up to make room */
		/* +2 for EOB chars. */
		register int number_to_move = yy_n_chars + 2;
		register char *dest = &yy_current_buffer->yy_ch_buf[
					yy_current_buffer->yy_buf_size + 2];
		register char *source =
				&yy_current_buffer->yy_ch_buf[number_to_move];

		while ( source > yy_current_buffer->yy_ch_buf )
			*--dest = *--source;

		yy_cp += dest - source;
		yy_bp += dest - source;
		yy_n_chars = yy_current_buffer->yy_buf_size;

		if ( yy_cp < yy_current_buffer->yy_ch_buf + 2 )
			YY_FATAL_ERROR( "flex scanner push-back overflow" );
		}

	if ( yy_cp > yy_bp && yy_cp[-1] == '\n' )
		yy_cp[-2] = '\n';

	*--yy_cp = (char) c;

	if ( c == '\n' )
		--yylineno;

	/* Note: the formal parameter *must* be called "yy_bp" for this
	 * macro to now work correctly.
	 */
	YY_DO_BEFORE_ACTION; /* set up yytext again */
	}


#ifdef __cplusplus
static int yyinput()
#else
static int input()
#endif
	{
	int c;

	*yy_c_buf_p = yy_hold_char;

	if ( *yy_c_buf_p == YY_END_OF_BUFFER_CHAR )
		{
		/* yy_c_buf_p now points to the character we want to return.
		 * If this occurs *before* the EOB characters, then it's a
		 * valid NUL; if not, then we've hit the end of the buffer.
		 */
		if ( yy_c_buf_p < &yy_current_buffer->yy_ch_buf[yy_n_chars] )
			/* This was really a NUL. */
			*yy_c_buf_p = '\0';

		else
			{ /* need more input */
			yytext_ptr = yy_c_buf_p;
			++yy_c_buf_p;

			switch ( yy_get_next_buffer() )
				{
				case EOB_ACT_END_OF_FILE:
					{
					if ( yywrap() )
						{
						yy_c_buf_p =
						yytext_ptr + YY_MORE_ADJ;
						return EOF;
						}

					YY_NEW_FILE;
#ifdef __cplusplus
					return yyinput();
#else
					return input();
#endif
					}

				case EOB_ACT_CONTINUE_SCAN:
					yy_c_buf_p = yytext_ptr + YY_MORE_ADJ;
					break;

				case EOB_ACT_LAST_MATCH:
#ifdef __cplusplus
					YY_FATAL_ERROR(
					"unexpected last match in yyinput()" );
#else
					YY_FATAL_ERROR(
					"unexpected last match in input()" );
#endif
				}
			}
		}

	c = *yy_c_buf_p;
	*yy_c_buf_p = '\0';	/* preserve yytext */
	yy_hold_char = *++yy_c_buf_p;

	return c;
	}


#ifdef YY_USE_PROTOS
void yyrestart( FILE *input_file )
#else
void yyrestart( input_file )
FILE *input_file;
#endif
	{
	if ( ! yy_current_buffer )
		yy_current_buffer = yy_create_buffer( yyin, YY_BUF_SIZE );

	yy_init_buffer( yy_current_buffer, input_file );
	yy_load_buffer_state();
	}


#ifdef YY_USE_PROTOS
void yy_switch_to_buffer( YY_BUFFER_STATE new_buffer )
#else
void yy_switch_to_buffer( new_buffer )
YY_BUFFER_STATE new_buffer;
#endif
	{
	if ( yy_current_buffer == new_buffer )
		return;

	if ( yy_current_buffer )
		{
		/* Flush out information for old buffer. */
		*yy_c_buf_p = yy_hold_char;
		yy_current_buffer->yy_buf_pos = yy_c_buf_p;
		yy_current_buffer->yy_n_chars = yy_n_chars;
		}

	yy_current_buffer = new_buffer;
	yy_load_buffer_state();

	/* We don't actually know whether we did this switch during
	 * EOF (yywrap()) processing, but the only time this flag
	 * is looked at is after yywrap() is called, so it's safe
	 * to go ahead and always set it.
	 */
	yy_did_buffer_switch_on_eof = 1;
	}


#ifdef YY_USE_PROTOS
void yy_load_buffer_state( void )
#else
void yy_load_buffer_state()
#endif
	{
	yy_n_chars = yy_current_buffer->yy_n_chars;
	yytext_ptr = yy_c_buf_p = yy_current_buffer->yy_buf_pos;
	yyin = yy_current_buffer->yy_input_file;
	yy_hold_char = *yy_c_buf_p;
	}


#ifdef YY_USE_PROTOS
YY_BUFFER_STATE yy_create_buffer( FILE *file, int size )
#else
YY_BUFFER_STATE yy_create_buffer( file, size )
FILE *file;
int size;
#endif
	{
	YY_BUFFER_STATE b;

	b = (YY_BUFFER_STATE) yy_flex_alloc( sizeof( struct yy_buffer_state ) );

	if ( ! b )
		YY_FATAL_ERROR( "out of dynamic memory in yy_create_buffer()" );

	b->yy_buf_size = size;

	/* yy_ch_buf has to be 2 characters longer than the size given because
	 * we need to put in 2 end-of-buffer characters.
	 */
	b->yy_ch_buf = (char *) yy_flex_alloc( b->yy_buf_size + 2 );

	if ( ! b->yy_ch_buf )
		YY_FATAL_ERROR( "out of dynamic memory in yy_create_buffer()" );

	yy_init_buffer( b, file );

	return b;
	}


#ifdef YY_USE_PROTOS
void yy_delete_buffer( YY_BUFFER_STATE b )
#else
void yy_delete_buffer( b )
YY_BUFFER_STATE b;
#endif
	{
	if ( b == yy_current_buffer )
		yy_current_buffer = (YY_BUFFER_STATE) 0;

	yy_flex_free( (void *) b->yy_ch_buf );
	yy_flex_free( (void *) b );
	}


#ifdef YY_USE_PROTOS
void yy_init_buffer( YY_BUFFER_STATE b, FILE *file )
#else
void yy_init_buffer( b, file )
YY_BUFFER_STATE b;
FILE *file;
#endif
	{
	b->yy_input_file = file;

	/* We put in the '\n' and start reading from [1] so that an
	 * initial match-at-newline will be true.
	 */

	b->yy_ch_buf[0] = '\n';
	b->yy_n_chars = 1;

	/* We always need two end-of-buffer characters.  The first causes
	 * a transition to the end-of-buffer state.  The second causes
	 * a jam in that state.
	 */
	b->yy_ch_buf[1] = YY_END_OF_BUFFER_CHAR;
	b->yy_ch_buf[2] = YY_END_OF_BUFFER_CHAR;

	b->yy_buf_pos = &b->yy_ch_buf[1];

     b->yy_is_interactive = file ? _isatty( fileno(file) ) : 0;

	b->yy_fill_buffer = 1;

	b->yy_eof_status = EOF_NOT_SEEN;
	}


#ifdef YY_USE_PROTOS
static void yy_fatal_error( const char msg[] )
#else
static void yy_fatal_error( msg )
char msg[];
#endif
	{
	(void) fprintf( stderr, "%s\n", msg );
	exit( 1 );
	}



/* Redefine yyless() so it works in section 3 code. */

#undef yyless
#define yyless(n) \
	do \
		{ \
		/* Undo effects of setting up yytext. */ \
		yytext[yyleng] = yy_hold_char; \
		yy_c_buf_p = yytext + n - YY_MORE_ADJ; \
		yy_hold_char = *yy_c_buf_p; \
		*yy_c_buf_p = '\0'; \
		yyleng = n; \
		} \
	while ( 0 )
# line 78 "lexpars.l"

