/*  For the logon and logoff procedures the following     */
/*  variables are predefined by the system:               */
/*                                                        */
/*  USERNAME       name of the user for logon/logoff      */
/*                                                        */
/*  PASSWORD       password of the user for logon         */
/*                                                        */
/*  DOMAIN         additional logon information (e.g.     */
/*                 domain or server name)                 */
/*                                                        */
/*  WPSAC_USERNAME name of OS/2 user                      */
